name: Build & create pre-release

env:
  DOTNET_VERSION: "3.1.101"
  OUTPUT_PATH: ${{ github.workspace }}/artifact/

on:
  workflow_dispatch:
  push:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch all history for all tags and branches
        run: git fetch --unshallow || true
      
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
            versionSpec: '5.x'
      
      - name: Use GitVersion
        id: gitversion # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v0.9.7
      
      - run: |
          echo "NuGetVersion: ${{ steps.gitversion.outputs.nuGetVersionV2 }}"
          echo "NuGetPreReleaseTagV2: ${{ steps.gitversion.outputs.CommitsSinceVersionSourcePadded }}"
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build solution
        run: dotnet build --configuration Release --no-restore
      
      - name: Execute unit tests
        run: dotnet test
      
      - name: Create NuGet package
        run: dotnet pack ./HttpBinding/HttpBinding.csproj -c Release -o ${{ env.OUTPUT_PATH }} /p:VersionPrefix=${{ steps.gitversion.outputs.nuGetVersionV2 }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package ${{ steps.gitversion.outputs.nuGetVersionV2 }}
          path: ${{ env.OUTPUT_PATH }}

      - name: Create release
        if: github.ref == 'refs/heads/main'
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ steps.gitversion.outputs.nuGetVersionV2 }}
          tag_name: ${{ steps.gitversion.outputs.nuGetVersionV2 }}          
          files: |
            ${{ env.OUTPUT_PATH }}AzureFunctions.HttpBinding.${{ steps.gitversion.outputs.nuGetVersionV2 }}.nupkg
          draft: false
          prerelease: true